# Base Python environment (slim) con Debian
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LD_LIBRARY_PATH=/app/open3d-devel-linux-x86_64-cxx11-abi-0.19.0/lib:$LD_LIBRARY_PATH

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    clang libc++-dev libc++abi-dev \
    libpq-dev \
    libx11-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
    cmake wget curl \
    libgomp1 libomp-dev \
    libcgal-dev libboost-all-dev \
    python3 python3-pip libgl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project
# COPY . /app/

# Download and extract Open3D
RUN wget https://github.com/isl-org/Open3D/releases/download/v0.19.0/open3d-devel-linux-x86_64-cxx11-abi-0.19.0.tar.xz && \
    tar -xf open3d-devel-linux-x86_64-cxx11-abi-0.19.0.tar.xz && \
    rm open3d-devel-linux-x86_64-cxx11-abi-0.19.0.tar.xz

# Download tinygltf and stb headers
RUN mkdir -p /app/tinygltf && \
    wget -q https://raw.githubusercontent.com/syoyo/tinygltf/master/tiny_gltf.h -O /app/tinygltf/tiny_gltf.h && \
    wget -q https://raw.githubusercontent.com/syoyo/tinygltf/master/json.hpp -O /app/tinygltf/json.hpp && \
    wget -q https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -O /app/tinygltf/stb_image.h && \
    wget -q https://raw.githubusercontent.com/nothings/stb/master/stb_image_write.h -O /app/tinygltf/stb_image_write.h

# # Build custom tools
# Build already done so we can skip this step.  
# RUN mkdir -p /app/build && \
#     cd /app/build && \
#     cmake \
#     -DOpen3D_DIR=/app/open3d-devel-linux-x86_64-cxx11-abi-0.19.0/lib/cmake/Open3D \
#     -DTINYGLTF_INCLUDE_DIR=/app/tinygltf \
#     -DCMAKE_C_COMPILER=clang \
#     -DCMAKE_CXX_COMPILER=clang++ \
#     -DCMAKE_BUILD_TYPE=Release \
#     .. && \
#     make -j$(nproc)

# Expose port (Django)
EXPOSE 8000

# Default command (modifica 'my_project' con il nome reale)
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "my_project.wsgi:application"]# Base Python environment (slim) con Debian
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LD_LIBRARY_PATH=/app/open3d-devel-linux-x86_64-cxx11-abi-0.19.0/lib:$LD_LIBRARY_PATH

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    clang libc++-dev libc++abi-dev \
    libpq-dev \
    libx11-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
    cmake wget curl \
    libgomp1 libomp-dev \
    libcgal-dev libboost-all-dev \
    python3 python3-pip libgl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project
# COPY . /app/

# Download and extract Open3D
RUN wget https://github.com/isl-org/Open3D/releases/download/v0.19.0/open3d-devel-linux-x86_64-cxx11-abi-0.19.0.tar.xz && \
    tar -xf open3d-devel-linux-x86_64-cxx11-abi-0.19.0.tar.xz && \
    rm open3d-devel-linux-x86_64-cxx11-abi-0.19.0.tar.xz

# Download tinygltf and stb headers
RUN mkdir -p /app/tinygltf && \
    wget -q https://raw.githubusercontent.com/syoyo/tinygltf/master/tiny_gltf.h -O /app/tinygltf/tiny_gltf.h && \
    wget -q https://raw.githubusercontent.com/syoyo/tinygltf/master/json.hpp -O /app/tinygltf/json.hpp && \
    wget -q https://raw.githubusercontent.com/nothings/stb/master/stb_image.h -O /app/tinygltf/stb_image.h && \
    wget -q https://raw.githubusercontent.com/nothings/stb/master/stb_image_write.h -O /app/tinygltf/stb_image_write.h

# # Build custom tools
# Build already done so we can skip this step.  
# RUN mkdir -p /app/build && \
#     cd /app/build && \
#     cmake \
#     -DOpen3D_DIR=/app/open3d-devel-linux-x86_64-cxx11-abi-0.19.0/lib/cmake/Open3D \
#     -DTINYGLTF_INCLUDE_DIR=/app/tinygltf \
#     -DCMAKE_C_COMPILER=clang \
#     -DCMAKE_CXX_COMPILER=clang++ \
#     -DCMAKE_BUILD_TYPE=Release \
#     .. && \
#     make -j$(nproc)

# Expose port (Django)
EXPOSE 8000

# Default command (modifica 'my_project' con il nome reale)
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "my_project.wsgi:application"]